name: sct_env
channels:
  - defaults
  - conda-forge
  - stcorp
dependencies:
  - python>=3.5
  - rasterio
  - coda
  - pandas
  - openpyxl
  - shapely
  - scipy
  - numpy>=1.17
  - pyxb
  - lxml
  - python-dateutil
